hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "efc154c12c41d109c1d2bcaaac42cc1942bd257aecc7dc6959efb5b5a7f870bf"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "3b9e19358031725e4474889df1028f48c38481980229d1914b48316672e6e434"

[[files]]
file = "config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "1e673e5c776fc34a35e2df497d76d9081ad0f0b5c89ded17d2fd57fe1969272f"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/cull-less-leaves.json"
hash = "e94813034405ef213afd650f1c7e9ff454a04435a8b72a74a73d470db41f5abc"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "163f49d5c78bf76b1a112c792e936a5915994c472985585a9463134971abd607"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "6555c8c1fc4d773df097895dfb76fe004377347581d5731f5408fb9d138585a2"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "93c4b423cf982419932b7085a1233ae956061f262fb732fd7f132a6c56817c9a"

[[files]]
file = "mods/animatica.pw.toml"
hash = "58134b8f4cca95555746efad25cc8a56c39ed57ba05f78d3aa61b603d378180c"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "79ab4fc83d9cd5db3c935a4374b0328d0b1eaa056c5315f93551e914ab4fdcae"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "eeec057d3fb7f0c076d271a1c3608b67d88895e59a18bb9b5a5fe604b65fc6e6"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "df21d4923d61c8d9199e602cca45695b7d17295fa8555f072d8d83045946ef3e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9a0135fbcfdc8f9efbed49fcb2e5641272ed218553cc37897eea94eb4fe47f1b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "0f24f7bd2057b70b6816de4e66922b64f8b6635dc603e40cc45d62646dc7221d"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "7494ae8e888e32baf72312266fdf53419c5f3b52908fde66dc0a160cdbed4e2c"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "39eb9db990032d949909f079ada415ffda18b372ec5d9b23ab95652d88474131"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a89158810657bf4a9cae0d45183a2ef5e7e327fb7e4aadb6743a6892370316a8"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "5cfdebf79480f71e84191358887f49eb8cc59b7d937f2e5be73fb8267606da2b"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "e6eff4533154c7715f8a1fbc8c8b9c940e63b5878f6ce39e7ffef050a8da202f"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "8f0c18360533351fff9237b803b1a91fb86cc9b00d56e61f116076e654c9f8e8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "8f0045c1f4b6a8bc0feeb64f6c95638383bb992b9dcc4cee0974ab85f6115b6e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7d0b378ccbc753946b078a94fd1cac24b7b906492aa45660d4686051397a4c17"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "515494490fe23d76d26b544cb1ae46dfaeb4662c11ea543d09fdded6c486f649"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fc96b91acafcbaf76bf94d2dff7d53a53fdbf52ccc6030acbfffe13a365cc982"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "14e87ff6253d2bd02697e46b4a9b5060465d72b71663def5236f829e30bac6d6"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "10f8e1b1c0b3072de6b4a54b73497737d7be4ba919c5a86a05dcee73ddb4950c"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "9baaaf98f919bf3258f50ae0b8552a53c16d298650cb90d48cbec6f96d1ef556"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1f6c74d7140e368e85df87d1bdbb4b533052488dcee7e23ecc1f699dfd2efe82"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7004d6d04c19eaa92fda0b47ac70b7c85987c47cc1431313014c5e9367679173"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "29b7078e678c6b90f607f9b09eaedc927fb274382963f39138b72243f2714224"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ec7ddc7195eaec44adb0a060c48d919bedb82775a3b683f8da21ab2eb6921ab1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "315648c1b6910b274d4a16bda8eba7ddf380d928edb20c0c36f3ff9776e30fe5"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "fd77358f512f332ee2113e5fd9d8929ff9fc5952c78f3693c98e27b0de77fef9"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "019e6f258127d947cf0b43227c198365b107e35d4e16e29ee8388986aaf62d77"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "e2cc568688c5bcd0e41235681bc34c5c9849f214f65b43324bc25022d9ad8c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "0232ec9d048fafef4d30897343834e6958580863be3ba53ce85abe80ba799878"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e37792db4c4b69e11243c7470f0f2a791dc016381e460cd5616eccb6b567b5ab"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "6de363a1d2baf1d4048a838de11353efa39efa396c6a8189a6e5ea368d7e9245"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "ec4bc8b7c36db2dcf3f19b4e03df845c36e18477739a34531de66e2fa75ef2dc"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "595baa2bb72f3af291c3e5afae919db7f26e4f7e2d73aea527fce947b861376c"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8649b82304ae952be04d0dda3ce6dac5648801fd7345336a5eba72307bcb0c5b"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "d8d16415897778ba9e6bf5cd74920edce456787f48c4e8fc6e2aa1d17fdffdc7"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "b4bfff726f0e2a2d9d4bc58e3a75ad3197c053264e8b0f474ac87e53fe9cfab7"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "b36d95833b8ec416f259a52e367f9e31e5f2b770be844f08abec6553335205c2"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "46af7d3bd6fec707eb0d9aac51c4cd1a85888266cf250b4dae7b2780487df7fb"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "249b71e84f094f716c122fbdd366e802159482d5d68681acb6e8d73ed9685bad"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "28f2167da063c1be7b1f4e534cdcbb446daa569cc32ffe1c0705663a9a06a5b9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "280cf7ad4ec95bd95eef81a7f327095c5f40e1b8aa45cea91284bfd19395d69e"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "f937ca0de07e36477286eebbd0b592920b5d8c76c0422d27bd2303732061bf5e"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "5d815da8dc55d64006acbb37437da7cd5e58e7a557e441ea7115d5d3f0768a6c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6a22d14251ccfb61007da299c1040bcb3904bd0cc43e5d1ba96536b94ed43036"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "a1c72f9ca36f2bd3f811cef6b4eb3cdd1d07e5c920bced7140ae237eba1c7ccd"
metafile = true
