hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "bce4552e7361652e8ba92a13a84e3c5eeeb20cccf4df4de15a57d1da7ff3aa12"

[[files]]
file = "config/puzzle.json"
hash = "21829a5d69be72b4202c975210a69c9331d75cd0cb7a9cddde56dac1131774ac"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "d16ef4b4dd9d1cfee220332e0246840ca3893a7c0cde99a299f717b63bd8dc2a"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "62b04eea085d727936f22e03d11ebadfae7490fd58da9048409b94c6ac21af9e"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "56e38e1d6039cbcf32c68416b60be42a4f5f3006c3caf50eb1eae1fc03580e86"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "c7983abfbff136519ffeca3ac75f4db10c81d7ad3adae6f4e1f9ad509a04c817"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "77663d8f0a7c937e80b3c7a01dab03c99f12ca954148ce4823d96d767ebb8933"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "51336712e25933a4b3ef553958ead09ccf02a7502b02b4240ae60c381b1858f0"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "8eac230e722a59915fa26ed453d780cd2034b65ec39a7ffe88135d16840c9692"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "a7c71647841d9f125dc7482bde82450b4d46942ba4fea673246fd956a1b499fd"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "51737ea18619d5d6f55a8c7aff5ac0375ab8387a68698baa650d4732c8e38df6"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "2fee62477522b340fb814284e126749bd7858d2f7c17a2400d09644e5c4d725d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "909e2467c0c277d63fe881ac80e44ea69ed85fe70c09665f2350cf92494294cf"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "adc94cd2504aeb8ba10ae4d39fc98c1f0fe5b06682b5b0943823d83a4bb5b9c3"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "0d539bf48acbab4079d41894b35a8eca1c68368738fd713de08acecae1dd8509"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/yosbr/config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7fa2fdbeb82f6838cdfd4e3c686f31aafba333e505509d75b98883fe8a17f450"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "c602ad2f5d370579a6f530355b2c60852fbbbfa6c230ebb568cbf79ec290e76b"

[[files]]
file = "config/yosbr/options.txt"
hash = "93c4b423cf982419932b7085a1233ae956061f262fb732fd7f132a6c56817c9a"

[[files]]
file = "mods/animatica.pw.toml"
hash = "f0463f1b50e2c2ab3c726b14236b22e07ce9be4896528ede9d51486a212a5c07"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "43c8d0c7b3642fe1748d07da8f3c6277a0a195bdc4043b9189fc53479e26b957"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "5eba39d9e5a05337908239be113ec4bc26b557d8bc9bf10e0c7d9528bcb71d4d"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "eb6cb8a8cde5c16bfe3c1f14353f362bc857621a9703579ff9aac154c8c975e9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "45e56b31dbb99cdb63c43338979328093b7369813448fd6875d13c9f81aa2799"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8c2f025206a96b2537a83f2d1fc10461e2a511e9cdbb8a120024299f88b046f5"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "932f6be6f81e47ec23ac4c2e717d273d6321d9f6312c6d52b239a9af38a7e7ba"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "d26a91a3a457dc46a9d492a1898ccb5f412b80dc093321150051b48da97794fc"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "24d93f8e349a4b3612bedf0a67df4f526ae33bc9f388f16840a3aa90b5ff479f"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "4e54e315ce46ed6dd72b5d6c70bd24bebd6a4e648b80afcbbedc8ef352a06ec7"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4b47562757100608c21dc1440a22175d83b1ebedaebf330c22cc04b951e7a477"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "31a3a63897d61718634cd371bf9b2aca8813441978053c25bbfdd9ffa01c30d2"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "013163e36e5fb78b68cd3f65764625ddc1e28e3f0eb2cf01e21e3ac64fba6b1f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "6f95b9e670d557f852a798489d7b5ec48ed8ddc7e8e1809ff06d4b187d17aac9"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "722d3dfcd83498779a8255cd6a7a36e129f24f5f19406951da5c521e2272bba5"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "ed38259e82ea5da07a9786886aa76e985c4603cfd578816b2ccab6f7ed4bc86f"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "5907619c0a26d32e4b7b2f6de98eddeb192b523adfb6765dd73c3224e7be175b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "c2814d761fc227d78759c88c38b37b3985fe4a36d18520a333965a1a9a601c2d"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "38a2c415fc59ca97c5297542b67daf477ecce294b3cbe2fe530193c879a252a6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a9a955be7b87637b8e748bf37f8c36a7b92e07d435d964d9a0f9a0c9e946f4b1"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "012a895c6e6def9eccf33ca2296466a6f062f4587016c465c962fa8de2869ced"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7331e591ff6290f533fac1ddee6e0caf3fb0941e61bfdcf2c61054aa7645dd0e"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "1127e53daa00cc93cc47e9226012c7121e9f44e83bc269b64699e8ac4894957c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "be8427f766253fce639d6e3e351b726a9b98e6ebc3ed4bec2023ea352bda0ae8"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "2a79f7fb98b7073c926c6f87a93473f5714cf82a2ace7f344e4e2de4a33e0233"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f29d10d90e0b8562293d61155c0cb445b83f454d59e9d0c8012fca59399c01be"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d18d104455a86bebd3f29deaf3458258674ea053d96e7b8fb5711cfea227fc20"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b181531817e2f079d5ac74f78c410d7e978d18c111a81b38a29bb3809102291d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "6b9a5755df72a262ba648f459c72d130211f859811b80b69aed1d47ea1a7aad6"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "2ffa6237ed942f5734c20ba755ae86592004f977cb6e3e64c34ca19bd60690e2"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "405de59ee1b659cce44f57af5e836307d2f6b29d6597baefbf3d95e77c582d9e"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "82312494cc4cb1b914968097ff27733905e6af5dec5829cdbdbc86e5c05b421e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "637533a15bb4eb5aaaab5a8fdc352214732202def3beedcd91a4e4e614a74f2a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "74942b197e40ee1a4852751088b911b7ef4b9dd4191c3029896464924a8d8272"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "39b013f54d6a8c48419a71557e6a3ec0fa9f350438b4ca26285261d66e017b0a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "106a5a4554f1d79b3158beea97e16108a318b940924e643162444630dbebecab"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "64cc3a69ccf183d56da3c42383918b90da3825877cbb13f712bc671487903120"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "216a3ddf71bdcbb9e75e6ee0c9a6d3a1aaec8da164e34ea252a0e3e0119d9835"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "187b4b7fbf0edfffc6471b5fb927db6a3555c2e8fd6cd03e2bd6be665848a202"
metafile = true
