hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "4b2d158dfd977ef6db626da315585e3ccca55d087cb8b8453ffc96868ee00a24"

[[files]]
file = "config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "1e673e5c776fc34a35e2df497d76d9081ad0f0b5c89ded17d2fd57fe1969272f"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "163f49d5c78bf76b1a112c792e936a5915994c472985585a9463134971abd607"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "aef7324d3c235a60b4e62983385d1b4bfd348f3a58995ab2a075e9ca0ac9d3ce"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "a2470fbc25f1a7df9833c57ca6588a356da86d9ab46881e5ce0e505239943fed"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "6555c8c1fc4d773df097895dfb76fe004377347581d5731f5408fb9d138585a2"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "93c4b423cf982419932b7085a1233ae956061f262fb732fd7f132a6c56817c9a"

[[files]]
file = "mods/animatica.pw.toml"
hash = "f0463f1b50e2c2ab3c726b14236b22e07ce9be4896528ede9d51486a212a5c07"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "48720fa4daacd4b092044f734342fb7ee07d6137d653c3a824d022bf72a08e47"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a54217c91466579ca4b7ef963ed5189c6c55d30c6a2c6a67f68ce07713de5ce0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "2c24f3b7bb9e171e8a3784e2c9a29c30f8541cff26e086962013c504a6c1cdb0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "5880c8495984f1236b8ce71b3370b31327b380b527d9799b1dcc45c70e538e93"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "1a65361cf2207ba6bad6eba3e66e407983452398c4ac5cbe5db0d8430b8a6496"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "39eb9db990032d949909f079ada415ffda18b372ec5d9b23ab95652d88474131"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "27f9b131c5f2db3267fe07cab7c104a5651cbdfbdc1f023374fe6d93f686f26b"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "bfd6f9ff0b08f5a856706cc4f9e8a803a6b32665e891085256b2f4fc8f58219d"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "406a3f78220ed5d7a4e60c7f89eb9a07e37dd30b4ce6fe684a697096dcd2118c"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "8f0c18360533351fff9237b803b1a91fb86cc9b00d56e61f116076e654c9f8e8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7bc062e46f4919feb0edac897a5db36ee1073abff7de2e90cd18301f8df0bb98"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6abf7d98d0bf709889ac20f1aef758fdc20762aaabbe31b277a88ee0f14bb3b3"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6cab3a465a9eda189b2fe3d3bbc2c1f3348e02d71c854758d84c51aa78f94b53"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d47762be5aaaf014cb93812502944dff9f1dc3466f3de96f4d4808da8e97bdee"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "14e87ff6253d2bd02697e46b4a9b5060465d72b71663def5236f829e30bac6d6"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "7b5ffc73c58d2fb595911936f4632a697b795f0e1c4445c09c6e74de6e4abb25"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "0150385c5eaea653a1433f4112afdd1b577521e71f9f2b7ab397af5e15aa391e"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "9482698f74ff6b14e036af6e2539f65d370482decd30b496faf574b6ea54b797"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7004d6d04c19eaa92fda0b47ac70b7c85987c47cc1431313014c5e9367679173"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "144c9b2dd530cfdf13dd3757c8eddcf6cfcc9631536dcabdd1378a39c8bdf47b"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3c5c24ba7c1af10c4bd3522efa8d1b89c88352e53382529610f81d50d46f0a32"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e416b18eebf514dea2014cf5c7fd3ee8493934a0b4e937509f15172ad271fde2"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c2597298dd5d160ca9161a12bcb5e933118cb66718b27c0945938eedb19dd90d"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "ef364a31e3355d3b920af2530bac7a2dc4ed69f78e83bf219a616730a63051fa"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8d8efd1b0fdd39724444d3f38573077f82b9f7091376d1c18a52404d7053626c"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "d157b9199d778da79cc8a08a57b4ba998cea1a57b75c54ca5b3a9892a05996ce"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "ce0282aa9a31909cba4c187bbf1ea0df1c0cd6077d21f89130116f6051a8d6ca"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6c8c93e74e46a0cac65179d027e9aac4eaebc44847604b0ff86644f3030116e8"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "fc3b3d32f3f0dfc641237b76e5e2a5b196a59eb9dc2d5a65e03d67200cc86f34"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "9d790daf7f139be1a7e771b7d70e4de5fcc5b3a4212b9dd7aa0ada308fa1c9fd"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "87981efb46e0cd7a408a1dddb1e80fd40c59ba0d9331953b0f888302a7dd3936"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "3572aa6d75c3ee9bdd85db71a6c43e9a996ce15e5371b2596c7017feddf56c9f"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "3f3184800ed92459d603cdd929b724d43e6c9705c7fee4743e1717de02de7dce"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "8be9dbb2abf2cdd5fb92f8fb64884a109fff9669c21e7f2c0aa1c31196ffd868"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c35d165125b8a1064f59e6573ce99fb62ce36142adbc476f3e2533256910ec4b"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "38d174b363d20977147fc4e9c5842d76fef3597556472cd4e8e75db3a6356445"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "174b7b4038141e84a8a08c29d742fe4608574955991b6147b0a5fdac4c6529ff"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0b1a53f585b616faa04cb2bccdb05e67c0fbc1887b209c191d4fb7c91d13cac4"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "f937ca0de07e36477286eebbd0b592920b5d8c76c0422d27bd2303732061bf5e"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "a1cfaa434b979b6f2778832353be5e9981f696f101e4c4d54ba0820bc1e1b1d6"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9ae6c555e5f5b610419c89d8259ef1f2c148f2efd6278e8e305b2dcbf96693ee"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "a1f0a2f11467455c534b84500a09f65756804ff4ea53797d654ef6726f5082c2"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "6ba173154c8fe78d78524902a420006e0f1af92533d990fc36d14e55f33327b4"
metafile = true
