hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "7bcf1f20ab9a1eca927b08e6d8772a3787d532ad82fe9b27d8b31dadd97eea7c"

[[files]]
file = "config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "1e673e5c776fc34a35e2df497d76d9081ad0f0b5c89ded17d2fd57fe1969272f"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore.toml"
hash = "4f5cd08148f87464a0f5e471787fd609a6546b653845954598e5a240b938a32d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "93c4b423cf982419932b7085a1233ae956061f262fb732fd7f132a6c56817c9a"

[[files]]
file = "mods/animatica.pw.toml"
hash = "58134b8f4cca95555746efad25cc8a56c39ed57ba05f78d3aa61b603d378180c"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "515e6bb16a175b9d23a85e9d4ea1c00145d3b85ccb44dc3d8762209538b5c3ba"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "bf75504007b250a62184fe13409e68fed230d0404b7ecec86f1bc75d9da26203"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "eeec057d3fb7f0c076d271a1c3608b67d88895e59a18bb9b5a5fe604b65fc6e6"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "df21d4923d61c8d9199e602cca45695b7d17295fa8555f072d8d83045946ef3e"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "0f24f7bd2057b70b6816de4e66922b64f8b6635dc603e40cc45d62646dc7221d"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "84de3cd780d9b310e855a6977b6b432b6ab5cb1da8a0c557341825ba31697af2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9e987ca790ae39c1897b96b29fee74907e76282dd8ecd015c66e5ad35a814c02"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "5cfdebf79480f71e84191358887f49eb8cc59b7d937f2e5be73fb8267606da2b"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "546930c86be75369544b8049e372151717ea13982b9fcfa3b8710737ec563da2"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5482cae1938340245adfcc540e2dd856d16dedf5f665d17c597e7ad363ffc194"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1bb84b9e770b26985fa2f9059f8289579dff784d1dcffc7ea77b1f0c12937ccf"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "226fb78f5592f34aab107001cb934f159090a4fbeaad2a15c1dc2af40c6ca0f3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "43d7fd09553ecf35b07ce2fe7958eaf4947b8fe4219afa25c99e42cea75fcfab"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "5edd45af7eccd8a626f72fa148a680dc2640c081bdc73971b17652c92b92780b"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "687092bc7e4b1c279932a9bb89e2a380181140373761c921c05c93c414618186"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "9baaaf98f919bf3258f50ae0b8552a53c16d298650cb90d48cbec6f96d1ef556"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1f6c74d7140e368e85df87d1bdbb4b533052488dcee7e23ecc1f699dfd2efe82"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7004d6d04c19eaa92fda0b47ac70b7c85987c47cc1431313014c5e9367679173"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "20a941f234eb3182ddf55862ecfc9b5f24911a27e88310f2a127dd0e8d675008"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "8663b25e8805cc38d50355590699b2266c2c8be50000451311c866113aa29b4b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "7e1a5dfc89f7f8c99397df79d5339e1b920b316c0860ef25d5ba06832455eae9"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e371e2a99c4958e0cd64914932a69562ef33748de04c1729999761423c4e330a"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "f14660be4c4cbc78a43756aafe528e956851119fcc5023139e82c18f8c520082"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "e2cc568688c5bcd0e41235681bc34c5c9849f214f65b43324bc25022d9ad8c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "c60d088f476eb37e15d88a762591d39874a99d80c729da813e0f4951e2906d16"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "0b35eacc51808809894ef78b91dfd614e056a34708e4bd2aa6f5ebeb7993a1c0"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "595baa2bb72f3af291c3e5afae919db7f26e4f7e2d73aea527fce947b861376c"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "3969af2963ad7ab059c1fc4485a579fe371b63f819878ad8407f5f4db51b61cf"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "ca77b2f891e554b3ba0db25f14403f7fbe9dceb7c0958e8077684b9a2d34529b"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "a7fbc8653864ad1160b2a05e6041ffb99fb1f9f34f67fe2f40a136121ba22b66"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "f25ee383f37be1c7033e1ba1e57a85c76b07ca59d4afcfcc234c12b9f5c4f964"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c7b00c2657fd545091480fbc7e48a2fe4be6e2bbe0711843a0328c969b0b7d97"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "ea10b64e72890a0b0fac51f24c33c33ecee7e1fbe4c5d1ce7df053f65c004ba9"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "cfbcb74eec1633a4941c2295cefdf6d1767cd9635494d5e2ec4351728468a3ab"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "7797b3e10400ef30c32c5ecdc028a81a382a6a809f6166f9d11a6e1a3f4b5adb"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6c1e39822b75339afddef8504a135345c119de71004ca135c442eeea4088d475"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "d05681b90cd9cf8b424ca4cd295eecbdbfcadf9fd2fc1af612228127fce7a2b6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "e77fe4473df0685a27bdc27f9a50c0dced4d298a2765301c2b1f0b11e078a887"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "f8e0e3a4bc7a85fa6563ff71de3d60d7c67cb2bdc600bee410974a685673e606"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "2f02b4f8f5b190c53e3cd318abbdc95849525e770353f7d15470d2b181330ecf"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "481ee07891029ab927064d9b9aef897b6c4bcde3e0882d8407adf2794a8745ef"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "ac13f7c9bc5f99ce85c6104f0aff4d36117c98bd7e6b8c124c7ecb21b94604de"
metafile = true
