name = "Additive"
author = "SkywardMC"
version = "1.40.2+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d5b697700e57f84bdbdebbf928761fb4ef411998e3687320ff56db40a9de8aa"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
