name = "Additive"
author = "SkywardMC"
version = "1.41.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "199c4c32891b45a3f3321a3d3c6d48c0076c2fb38ae93c3e75eaea037883c99d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
