name = "Additive"
author = "SkywardMC"
version = "1.38.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77a151e90eb158e112a8eb57db65827f0c1a8f503e04fb9a034983d36cbf9b69"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"
