name = "Additive"
author = "SkywardMC"
version = "1.41.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6641ff1ea7309a7f1b6ac17014a7b671828bb32c6cf5172f25de73a867a1331d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
