name = "Additive"
author = "SkywardMC"
version = "1.41.4+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "186c2b13110df8bb82021836157bec70f73aa51cd0b1a0b6f64c361a4c21472d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
