name = "Additive"
author = "SkywardMC"
version = "1.41.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52d12b821b4ad2d80d3d158a94f3621656f30815a8d42da4a5f1d1906528b9e6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
