name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91fcd523cf28f715c45dfd2d4fa74ffc518545ee609966310134808b093b755c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
