name = "Additive"
author = "SkywardMC"
version = "1.37.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e09e069035d495ccf5cbd027a49c1bd4e530c4470404e36585a9596cdcc7f58"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
