name = "Additive"
author = "SkywardMC"
version = "1.40.2+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a24cccedce6c992bac7cd734a240eae64e557c33832c982ca0d49d74543d0385"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
