name = "Additive"
author = "SkywardMC"
version = "1.41.4+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f609b144b0d2ca3d5480b35f17c961eab622bbe6651efdd436bef1c7af389ef1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
