name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d96ddadb9630dd4c2c9fcfa0050c76dc69d7abcb446f4fda9fb4bc03b4d6332b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
