name = "Additive"
author = "SkywardMC"
version = "1.38.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dbd20e04756c6fbdaf5ad8580930ca9c3f7905d30f2af54322cbe867fc0e0bd"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"
