name = "Additive"
author = "SkywardMC"
version = "1.39.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1bc72fbb76ff76a275ae44bd63c9b831c4f2953b90cacac948532a45c8ba65b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"
