name = "Additive"
author = "SkywardMC"
version = "1.32.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "240efa5791cdb3acfb0dbe6a66bb4bc5c6fff12addfbd0e5a2b6efbf6883e654"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
