hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "8c1cccc546f73f86c0430dabd606f4ac4c0a3a31a51c8102bc3a7391ddbf8099"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "1e673e5c776fc34a35e2df497d76d9081ad0f0b5c89ded17d2fd57fe1969272f"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore.toml"
hash = "4f5cd08148f87464a0f5e471787fd609a6546b653845954598e5a240b938a32d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "93c4b423cf982419932b7085a1233ae956061f262fb732fd7f132a6c56817c9a"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "fe5f1014f6711013213e118c9defb3c41357d0ebdaa658f15d35c76839e419a0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "0bacd265b682a6f3cf480449af87fbac592033a158b0669fa78c23f27ec2fdb0"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "04caaca613928c8d4e1d3015332a74a43be6ee0fd7693011d2aa91f56d13f768"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "8a8d6af7aa8cb063e2b8fe7b29cf20a5f8384e1fee0ed7bb1a4b32d6ff73e919"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4700fcc4fa1f3565cf3ef54dad8673bc940d83652b07dd2461c88b4a5b38aa16"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "72e6b0ace0205854b277730895f0cccfa9c4f686278c472fe0a3f625c8c7a974"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "9b3c26462690df72c3c0485faa3589ce869f5a1d00331db881a9ba19ac18c2cb"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "f32c30de1ae7dbeeae00b654eb15ea358c6d26f631dc292bdb88dba9c30a8cc8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ef5594aca1039c06c502f9d3f4a709195b727abb3b2893652dfe38d983ff87c2"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "01d55263030ec2c1025a7e2a577cb4a17600815ce1420792c70053359fbc9143"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "91f0f362b62cb49dd70f3effff7b0b813a01a99ccb272abb36f385c41ff931c4"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "e58c8372935514b074cbfc4771c998e519ed5c94ac0445f7f210d64ebfc6e5eb"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "03ff6ba60d550b285dadec9bf0344e81d5c188648d383e00f869abdd01a19ab8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9c36c83ffb26de00465c63f53744c9dab43498402136a422bfdf88bbeadf6689"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "3d0bf4d56ea941f856200934fdc2fb4952fe513d469f47bdb5fc586f99f16097"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "fadec41bfa49c1db8d973e56b564dfaa592ff19dd106e846382b23338ad67242"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "7004d6d04c19eaa92fda0b47ac70b7c85987c47cc1431313014c5e9367679173"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "bfd0e9e0e3ba950e458caf9687e2ebbf0a3c4e1f2f97259a25242f5649e808a9"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c79a98c5013dd8f1e219043aef5d77a969f9703455c5d4ca50e366ba943d0295"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "743e2829fd76c27c711c54b045880f64f9e67444c78476096fec18879c441764"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "698d4ef94817abda13fd1b052bec4c5ed51fe7f84fbc218bbe545ed2a23a9622"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "1798a6630002cf17d1727c3c6b77b8e671d52dfcef3fbfa3cdfaed0eacafb53e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0d50516f7ba174f3bc8fb4c12e1200d82649ca5e3b3f42de408d420bfa13fd2d"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "3ba523b0e2a61388644998f4ce0e34bffe2b4bbe59d5b4bd8e467e52fc4fc21a"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "78946e7851174a7462125185cb6306f5bac4fe5b90a3f4396cd8a79d56084661"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "8df15e4c82204449bc611392e13ba20e6586e9be5aedc65260deead2de0b00f6"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "03b88e6c07796d391b9ea91b68af2a0bc3bf66b87d7f1faa298d581be40cc365"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "69a406e989e57db6c14ea72ae7f9bdf31114535f27979b3d703bd8a1532f0d58"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f59ab3633f781c5b5af3234f694da4c4d5195c9211b1ece7e410b54ec1a183eb"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "6a4b1120695a7c97e759c277e1a275f5442859d4031edb670248d8803dc0377b"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "2912afb1010c3ca055faa50056ce2adf233923bb6330e0802b7f552b1fadfc6c"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "375ae78c4e4cb43a9a172f6866de6011d4d01eaaede76d23a38a157663e43ff2"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "8724da09ac15ed3b82a72aaebd2343101a898f3e611cb6adc0ff65a27981fa5d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a18faac8593412b5ef8ee28bf49ebf7fcb16197aa4d2396dd0684b7defeb0b59"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e43454084839b810fa0fbc9a5193fca1d72470ecbc06d2138538306f08cb2849"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "1c137d989a144a658c564d77658919ed50c6a09ea8624037976425f0b4c7128e"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "80f50873bae102f72d50483a54c1e4dcdf310ee7e7fbb6d48f90137b24d23124"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "315714be5acef01e67eae71e664b3c2a693d82f551f38c2684a8c0197d2a59b4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "712ba18d98e6e549968641e03cabc50604c362e1a9be9a574b7ab4025b13501c"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "8f3093e175ab439cdf381c7f038510e73a07698cc9e9c7c370cb327bd8bbd3cd"
metafile = true
