hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "7b0f74783df53abcd38de463c7b79582d8e75737e5ccadc07ceb823106cc7dbf"

[[files]]
file = "config/puzzle.json"
hash = "017213d817c551c6bddb0cf3a1344ded1747abba66bb758c9c9effc39f0d46e0"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "1e673e5c776fc34a35e2df497d76d9081ad0f0b5c89ded17d2fd57fe1969272f"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "163f49d5c78bf76b1a112c792e936a5915994c472985585a9463134971abd607"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "54008cb6683821a7666db20867e55f71b7f90f101191cfe8fbaf1eb38f975e96"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "624ed4c30777968887c07194cc265fc66aea996a20f55c32f0df861bc8ccc5c5"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "a2470fbc25f1a7df9833c57ca6588a356da86d9ab46881e5ce0e505239943fed"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "6555c8c1fc4d773df097895dfb76fe004377347581d5731f5408fb9d138585a2"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "a8f46cff138e000d4ed4505cc2bfdc5cdc6e8b5588fd1b1e2d6222cd21e624e2"

[[files]]
file = "mods/animatica.pw.toml"
hash = "f0463f1b50e2c2ab3c726b14236b22e07ce9be4896528ede9d51486a212a5c07"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "4c712d7ad6d2ddb130b845c3b2c660be7cb7795db21be00b130443730719305e"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "2cf2d6c7683cbaa8d4d91374d5a92e6166176aefe5e0d7a0a2714c9321f8add0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a89dfcc985612a275975d4823a24fc3dceb244bacb2e8f81bd459283bf1b9fe9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "bb7b31de1f5c7941aff59030d59168a5971e8c47884bcd8905637836ff97ce46"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "1a65361cf2207ba6bad6eba3e66e407983452398c4ac5cbe5db0d8430b8a6496"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "5d08ee5a9dad38ed87772d437d7e1779fecc0baa4a0e6d33b324bce9908c60ea"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "6a4afd7b42387477795e73b17b8963ea313ce6f8a960343a2579ff0b41544beb"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b8270928d44781b9e59982d376bb3cc0d24089ceebef3c79d3e1e881ba7ece60"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "8f0c18360533351fff9237b803b1a91fb86cc9b00d56e61f116076e654c9f8e8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "e8b644e3f024030e5477aeb6716cb1b9a0c920abec81d2674a5054c25cf631c3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "625dddd14bf47324a945452cbd92e913877bb574883b086a73aa6fc07740ac44"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4acc71ef74d7bde9aa8a15932d1005d74efdc78d6c373553084d98dc332fd8c9"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "ed4487cc1613cc53daa5188730653a4720728971553315dcea7205b28f914f1c"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "ae83dfcccd580352eee3cf509ace37f67f1bf0d2862d2d9c9d64d8909892d2d4"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "26b473edf76a38c7f6f883381b6a42a33eea992501f26c46bae8b6149c86e234"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "bd0e1bfaa16148cd114e33d11ec8f742979ec5b9372f6baa6a335a316659e70e"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e416b18eebf514dea2014cf5c7fd3ee8493934a0b4e937509f15172ad271fde2"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "eb0d9a1475b609eb82f26d0440846d52034c1aef8fcc21ee1cc327dc52648f7d"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0e0ad3001c99ec281023ad8fefb7ace9931cb8cbda6d4ed18abf2b47c02320da"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "a626674fc1092afe5ccc6cbf4856c09119e42395494f1c3862eed2ab17da0221"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/loqui.pw.toml"
hash = "fa0de9ccb48de8fa13f70939277314d3a538d3a71b88abe21197cb6a2189fd63"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "2a79f7fb98b7073c926c6f87a93473f5714cf82a2ace7f344e4e2de4a33e0233"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "160ab5c829c0af5fe32eaf637f13f953daee5eda164ca72833a8cee572e62e89"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ef9c4bc27256d065df4feaba2bc05883ba22987c41cd48786070d37ae85cc8e1"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "0b3a68ab8700e95288d2eec264ac188f0fc9fe1c7a3901c9dbc06ad207c90624"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2440a2e6d0ade6bc4ca8d3677b59312734dd22106fc6fc5cbac5c24b0ba2ff05"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "8c9fe2bad735008dfbee8a690049ac2a6612f06bc6dc735434fcbb8cf5e4b34c"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "a6e087aa1beacb72cbfd77e442c78329b8a3c8af71cd3833078ff4cc7186d64f"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "47217cc1489533f668d622f2078351a61873be573311a9a94be7293328a849a7"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "5a6df3930d69602402cd13bf860195ac44680e2d4556e8d1254ae730fcb4b0f9"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "0f9916dcded3aac68d56113e9617bbe3db5ec9036bd9bba784bc40a961b0c9f0"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5379b1da9fa50def37ede26e66dd963de3ce6f8576cd60a6b117998e09a5597c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "cd49906a91e2ff1c11acba79192d609c232f2f73d82cc6a646e7338c8e76aa8a"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "dbbeb7a8f32fdbe0d5e44a8c7671ed2297ee8d12d4610500ac54742e70b4fb53"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "78543b5c34480b62a11f80ca2b383608dbb2b116ea4186007af7ee6b8d8203ae"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "10eead85b57a4646c27aceed0597cca489cd4ae5e4436bb69f9b1b428325ef89"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "f1f74f07924a5b0eb57e7c662c2e3f8c56d50eaee0dc2cb4cb40985af8eb9cf4"
metafile = true
