name = "Additive"
author = "SkywardMC"
version = "1.41.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0897f69b51fc172d928f57148dd018c36fb427bb20f60b9bf6b71b431dbea0f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
