name = "Additive"
author = "SkywardMC"
version = "1.39.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f6f0c4ace60978634d34b79a3459067c8dff53e38e19129314382ca2254728"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
