name = "Additive"
author = "SkywardMC"
version = "1.40.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97e20833dc185641cb33f319f8c381e9db5204335dbc4bfd18f07bb3d6d499be"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
