name = "Additive"
author = "SkywardMC"
version = "1.41.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2305eef60088bb39128bbf9d7db6cb58cdc0e6710d3a522ef7f91971d081deca"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
