name = "Additive"
author = "SkywardMC"
version = "1.41.3+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46ea46ca4660d631b491b66bbe2d9025619d4f2370bc4f4dbe09112cf11afea3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
