name = "Additive"
author = "SkywardMC"
version = "1.40.2+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a637980c5f737b4d4fc3bc5e7dd1cde85344a0b0259d01fa135472ccb3cf6e89"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
