name = "Additive"
author = "SkywardMC"
version = "1.39.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8403edb405c673eadf4c6dad7f4141dd5931b9fb1ebbf01cefbb7acc6477380c"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
