name = "Additive"
author = "SkywardMC"
version = "1.40.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95d7761eb7c442e097243211119d218ee98eb75d77fa1eaf44744982862ac8b1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
