name = "Additive"
author = "SkywardMC"
version = "1.41.2+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "347b534dec75b4481158ceef5095687bb85d50b566807a56a7e3457fe9700efe"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
