name = "Additive"
author = "SkywardMC"
version = "1.41.4+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "060779b78712d32267497e229c0bb8be8384c3185602c9fd5f7a76a7ecdea799"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
