name = "Additive"
author = "SkywardMC"
version = "1.42.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e2c5cbc37f470a86121176ec70629b63eb9f422a3c9503d09b6cb681b4382f3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
