name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0e78adf13b50a1f95a9122e298695ab5320848fbca83f56d248f10cd3d7ad9d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
