name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "782a0e2102d10ca33ab7c3d2c5d841f7d1277c9d27040d8bf8321389095b7252"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
