name = "Additive"
author = "SkywardMC"
version = "1.40.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62acb179a95f36cb948a49cb9e7226ebf76a2294f88584a5e93b9f19dd2968ea"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
