name = "Additive"
author = "SkywardMC"
version = "1.38.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0879a5e2a209c04647e46ff4e03acc6676c7056bd30cd4d0dd5c9affadf37e21"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
