hash-format = "sha256"

[[files]]
file = "config/capes.json5"
hash = "b0e11760190870b23a50e68018a3792e6ad3929302bb2917db21268a20f858af"

[[files]]
file = "config/cem.conf"
hash = "c869b1e1cf73b7b0d5ca03e4657fdbed845d85ab5aca0449248fd144545ecfb7"

[[files]]
file = "config/entityculling.json"
hash = "d1263f28704a153ad67c648fe20b37ab8c9d65f279b2130d29a4ce8be8ad9d0a"

[[files]]
file = "config/iris.properties"
hash = "a9a6c0ecd319c9417e35b3b17f91de37075001803296dc6fab2a52f888a342c8"

[[files]]
file = "config/modmenu.json"
hash = "16e48fe05ad1fb0c4d363d2d35f9d2c23c6895d60ee29f9f6eaca81e4e4ba9e8"

[[files]]
file = "config/puzzle.json"
hash = "6d9d65b9e92519e09931488219a9cb618e67bde4faf06c192e6243f3dcbc09fd"

[[files]]
file = "config/sodium-options.json"
hash = "b41ffcbb5a3a65c822c3031ae1721ee445f64c46e4796298030342875d34038e"

[[files]]
file = "config/tr7zwDonorSettings.json"
hash = "accf3ae12dbb30c807b81d59a5310784aef56bb992cbd287fd6117aaf144fcff"

[[files]]
file = "mods/animatica.pw.toml"
hash = "73386e4a41baab1188f2c594ac9efad42ccbb3c02934d21cc86461b616121954"
metafile = true

[[files]]
file = "mods/bedrodium.pw.toml"
hash = "98e7a87ca292ed3df4a532819499a9bf9e6d1bada60a45db4d0da44e061c36e1"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ee23e2c15742421bd42726c87c1212571faf021af09ea1bc2974b63e5386fb90"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "3b2c1ac53b3aed8e5d0a20ed50a663e8c24948216ab93acd4135c69b3c2fa1e1"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "753859b58aa7a674785b3ec5a8080c2142209a50185cc3dd5ab90c7c6a38f5ee"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "c47b4e6dea49ed224870b70e2101f7dfea59c63490cca1d5f5a1dd43b18c56ef"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "c49d1423a5f2563335fd5719862a861c8ae2c9cbc46598e767c3e2fe1042ecae"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "749bf88d67ff9ddf272dc48d82402dd61ea2812238dfca4feb1fd78440675456"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "ac2207cfc96eabeec2650f09d9ef72d2597fc7438edc9cbdaf5fbb2ba43bfde2"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "073bff49ec9e664b669794177329cfbeef3c3d91d5c0660cd01144a640e0338b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "51949291a0f29beab1674ac3e5a6736946042b727ff7d911767f8e44fcd50a8a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0164a54948e8c8b4220f1b3f8a41a1c450050fe19e04256ed96e36f58db019d3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "8e91eac9da646c5458d00fb68ccf0887bf815947ef549cb19abebe1e6cec5c72"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1d533d748141c829666799492b2ee7e6f13dbe54da7839b3e7da1f293ed2f3a2"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "ac0a425f01b57603d143e65eebba8b53078474c61f8f0a9a35ab2bbd7ed3a931"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "87f056062378f276e55d07a577ff6c734bb9af9ea2b5591c424f7c381f82a552"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5dc09aa39836e32c785297fd6e34c70e1ca9cb80264da8b088e0bc166b69d9e9"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a348ec1aec5a10f7235d6741e08aea583e042049eded3d6eafd97a0688a891c0"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2bd6bb34cc34e9010c35d30ef21e71fa63386c6a7b2bbe16f7c1369db10c693f"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0ab0925b9d00ddcf75dc5077fba4eee2c825945a7590750e1821ba783fb26f37"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "3ffe2388740cc111a332082f56e37bb4b95764035dfe5d6dff81db8a35d4cc4d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "443104f3ae619456aefa8eaabf9dbfba4c0a227435fc7c6e2f4c89370bb6786d"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "9bedd7ca66c806a5bc8bfefc04ac3a4665bccf3a6672e3a4ebd69dd752c5ee6f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a5c86b836f2213ad4db415d13f6ef5caa379ce348605a29224eb7703b81f1f95"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8146180d1612a9ec226fb5981f0a95167c19a4a0e6a188eae93c94e5bcc8ea47"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "9413d03007564d3eaaf8ec25eabe10d5e741ff0c68017c2d2c824a8ed9be18d3"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "ac7920d31fab63ba23daf953a44750930f597bcd3bc11121845541e934d0aef4"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ae4b4112db3f14bcb9e8dc10ea06e83d84bff4d9ad2a3dfd74533c1256b98218"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "3f2148f425622b9226aac1a5ea41f6613f9fdc0f484eadd72d30714ab0a73895"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c77f162c7072a9bb922faf3bd5f223ce4f57973d531cc32484a7dcf72d2e1f51"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "bfeba0ef83ca25c52d9c76421b57c6b53bba04aa17d7df0ab85bfacfd57efcd8"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c6c963c8c9389d864664aabfd259e9b3909c274b56b2ff1477dac551216b3a28"
metafile = true

[[files]]
file = "options.txt"
hash = "ee3866679cc972da85e7ea9e465363d37813a17862a24116507bdef8ac23c00f"
