hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "e7742f402470379c17668cc4df0cc161784f9fec9fe58eceb28877536d1db1d8"

[[files]]
file = "config/puzzle.json"
hash = "21829a5d69be72b4202c975210a69c9331d75cd0cb7a9cddde56dac1131774ac"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "d16ef4b4dd9d1cfee220332e0246840ca3893a7c0cde99a299f717b63bd8dc2a"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "62b04eea085d727936f22e03d11ebadfae7490fd58da9048409b94c6ac21af9e"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "56e38e1d6039cbcf32c68416b60be42a4f5f3006c3caf50eb1eae1fc03580e86"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "c7983abfbff136519ffeca3ac75f4db10c81d7ad3adae6f4e1f9ad509a04c817"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "cdf61af100d8a29e9bbf26cc1b7ad8ae29c82357831705a97bb1dffa8ab386fa"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "51336712e25933a4b3ef553958ead09ccf02a7502b02b4240ae60c381b1858f0"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "8eac230e722a59915fa26ed453d780cd2034b65ec39a7ffe88135d16840c9692"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "84825744a3386b5194422e99eba7a3f49f0b29d4a9eb74a11921fd558d4571e8"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "bd5d8eaf56e9ddb5196a85a5713db7e213ed88c8895958f33c01464a1cb0a1d3"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "1dc6a3aef057f6d08a802abba3c64af5d604078059787da31d253544c67e8904"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "08c78ab862dbb711eaa56f41bbf4696e3fe7d7c5882e864bdf6586a0e67234a9"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "51737ea18619d5d6f55a8c7aff5ac0375ab8387a68698baa650d4732c8e38df6"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "909e2467c0c277d63fe881ac80e44ea69ed85fe70c09665f2350cf92494294cf"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "0d539bf48acbab4079d41894b35a8eca1c68368738fd713de08acecae1dd8509"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/yosbr/config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7fa2fdbeb82f6838cdfd4e3c686f31aafba333e505509d75b98883fe8a17f450"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "c602ad2f5d370579a6f530355b2c60852fbbbfa6c230ebb568cbf79ec290e76b"

[[files]]
file = "config/yosbr/options.txt"
hash = "a8f46cff138e000d4ed4505cc2bfdc5cdc6e8b5588fd1b1e2d6222cd21e624e2"

[[files]]
file = "mods/animatica.pw.toml"
hash = "b494eb2872c5eb3c498e147be24a62e2c62485e375b9b99c15ae0faf8f9dd2ca"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "43c8d0c7b3642fe1748d07da8f3c6277a0a195bdc4043b9189fc53479e26b957"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "d9eedf6b968e18479f2d9819859e5d9e8eea0876c066ae4238a4672482a34efb"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "83d8a8865dfe81276fabc0c7085106a760608c0a3d569716fc77b3d0cb4d4c0d"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "eb6cb8a8cde5c16bfe3c1f14353f362bc857621a9703579ff9aac154c8c975e9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "156942df991662545265aae10fafa4b64bc1ba1226670be03916e58894671089"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4cb02206331c9a6d207681b2e40b4b8648a462b0c31e6e634200a01b592b1d3d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "dbc9321c870e69e867837cbad4f0c1dcf45c3c27d2ee230f6a6868cde2f9daab"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4b47562757100608c21dc1440a22175d83b1ebedaebf330c22cc04b951e7a477"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "416fdc912dd2bbc125eaaa322e5cc3536aaf341264caceebf1ee129df48b9c77"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "0c49c30afd27b0a2cf79b4487a31143a313e847ad6eede7f9d56d7644313e61c"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "3a58bb01d7089cb2b58fa5486063f9d4fc9c26f235593857ddd933515960e59f"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "0e72ac12907f4fb5a499a459cc2c64f9225a0c77ee59e76c9360ff0d3479aea2"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "5907619c0a26d32e4b7b2f6de98eddeb192b523adfb6765dd73c3224e7be175b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "c2814d761fc227d78759c88c38b37b3985fe4a36d18520a333965a1a9a601c2d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "8b204c352fbc477a8591ca32376b004fdabcfacb12b570a7a1826cabd550bb93"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e6e746d0ac4dd170a8309e7bda19ad05c74d6352c1569f83f4dd01e2980674ff"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "cf6adf4f1a4e8f56e592805ea37d1120b42ab5389da6f423040639cb229f48d0"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "5d08a3b2006167423205d9db02be4afb8e8441092e012961390fd3f4bfdc100d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "f573cac2ec9cd88456c545e177753791c91a38ba0a46c4ad4c87e5a7878664ea"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "be8427f766253fce639d6e3e351b726a9b98e6ebc3ed4bec2023ea352bda0ae8"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "2a79f7fb98b7073c926c6f87a93473f5714cf82a2ace7f344e4e2de4a33e0233"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "78e5ad156b8c0619fe9b2603c3d26423985c4f8437dfce3dcdce4d7463a1ca79"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b181531817e2f079d5ac74f78c410d7e978d18c111a81b38a29bb3809102291d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "0241aaf8419884f43f529223b52e274712b109557e065846b953ab91953f2cb7"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "2ffa6237ed942f5734c20ba755ae86592004f977cb6e3e64c34ca19bd60690e2"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "977fa64f69701ba5617640bf048abc10257ed00ddba615ceca1b52e65e118c2f"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "8cacfddf1fba2b0254a13cd0c10c3ea06ca8bede720d728b1369f47bd91f7589"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c48006ba1c8c4ab44d43ace55bac28c14a237f48016d990b4c2057255a60477a"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "82312494cc4cb1b914968097ff27733905e6af5dec5829cdbdbc86e5c05b421e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "637533a15bb4eb5aaaab5a8fdc352214732202def3beedcd91a4e4e614a74f2a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "74942b197e40ee1a4852751088b911b7ef4b9dd4191c3029896464924a8d8272"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "a358d855d607dde44433097b6a054855143cb2f023f70c23020427b3548b9972"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "1c0b40f9eed2fdcc55d1e4338da7fe18b06061e829f349aeb12bb22a813a4935"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "37c5d5ea5d8c26d988a1de62ab9afc54fa9d8febf276de57f087a1642265ebfc"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "64cc3a69ccf183d56da3c42383918b90da3825877cbb13f712bc671487903120"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "62af13d9f72ce550635e6a288cb94c82b9d5107eefea577d7135508bc593cadf"
metafile = true
