hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "2be6a9d9492834668b2bc88735d01820476a6c08d7367be6f29aba26dbdb07bc"

[[files]]
file = "config/puzzle.json"
hash = "21829a5d69be72b4202c975210a69c9331d75cd0cb7a9cddde56dac1131774ac"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "cdf61af100d8a29e9bbf26cc1b7ad8ae29c82357831705a97bb1dffa8ab386fa"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "51336712e25933a4b3ef553958ead09ccf02a7502b02b4240ae60c381b1858f0"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "84825744a3386b5194422e99eba7a3f49f0b29d4a9eb74a11921fd558d4571e8"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "bd5d8eaf56e9ddb5196a85a5713db7e213ed88c8895958f33c01464a1cb0a1d3"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "1dc6a3aef057f6d08a802abba3c64af5d604078059787da31d253544c67e8904"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "61d20c951eee5418cafbc19c811a82dad1d019a2c86a764209b681bd6319a49a"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "0d539bf48acbab4079d41894b35a8eca1c68368738fd713de08acecae1dd8509"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/yosbr/config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "6ccf73c631ecef6b9a5b6a9cb67b4ac117a3b131ce0b4a884a3b4ec1b537aa0f"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/options.txt"
hash = "96c989dd0d3e12f5d042f0964452365a9add38effcd6fa3d079474d25420d524"

[[files]]
file = "mods/animatica.pw.toml"
hash = "b494eb2872c5eb3c498e147be24a62e2c62485e375b9b99c15ae0faf8f9dd2ca"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "eaeef66044d551eb98b20b5c293d9c396f8342f17bc76bb0822cd90ac56b95bb"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "83d8a8865dfe81276fabc0c7085106a760608c0a3d569716fc77b3d0cb4d4c0d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4b47562757100608c21dc1440a22175d83b1ebedaebf330c22cc04b951e7a477"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1a28f950f0e26b507b2613224c0f49bec23d1b515f51cdccec3abb221fc8ab08"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "f974bd1b21f7b3c9046c4ccaeb8ed1cbd36df72b080c5deff86f8d7f5774ce07"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "3ecd59b2ab957aadc6759fdb82b82d63c03dfef49c1199f271078659e94cdbf1"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "c2814d761fc227d78759c88c38b37b3985fe4a36d18520a333965a1a9a601c2d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6d8f457e49c2a578262d091817b5571897cd73a3bc58db33bac3c60f13d67679"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "79317bd0768bd7d84ccd9f22db1e56d4a4e8e3c351e3192f719816abfaed1b85"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c880ebfe6d340e4da7fe935f1a3cdcff84d3db7f4efe8fb3d12839b6d08c7aed"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "ef2f37f8f7eb3481d6d379b54b6607fc7e2b51be0a8fabeccdb0e39ae01cba0c"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "83a212a71370bd6cc3133a44aed97da0d03492b525f4f0aff5e5a76922608b0b"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "3ffe2388740cc111a332082f56e37bb4b95764035dfe5d6dff81db8a35d4cc4d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "be8427f766253fce639d6e3e351b726a9b98e6ebc3ed4bec2023ea352bda0ae8"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9966fa77d57235f7460b84632e7b89188b2944787f23214f87a10908f5aed867"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b181531817e2f079d5ac74f78c410d7e978d18c111a81b38a29bb3809102291d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "d1a855b30f796a2a57faca3702c7bfafb353ddfcd597bca2d8c01fb86f010bbc"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "2ffa6237ed942f5734c20ba755ae86592004f977cb6e3e64c34ca19bd60690e2"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "d53ea077dd824788e114ad1b113d413504cb40a8680c28d9b596ad1997c3386d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c48006ba1c8c4ab44d43ace55bac28c14a237f48016d990b4c2057255a60477a"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "82312494cc4cb1b914968097ff27733905e6af5dec5829cdbdbc86e5c05b421e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "637533a15bb4eb5aaaab5a8fdc352214732202def3beedcd91a4e4e614a74f2a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "74942b197e40ee1a4852751088b911b7ef4b9dd4191c3029896464924a8d8272"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "3a378c86d2ff9d63eb420ef3a0473c9282b29ffb2eef087ce7cde868cef9eff1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3207f43011f1e422c2491333eb3882d761056c76d463cd2e0f7acdd4ce85e97c"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "72214bf1c5210d1fd5d47f5fe354310ea7d7e1268eb48574c0655d6d4f4d5c42"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "187b4b7fbf0edfffc6471b5fb927db6a3555c2e8fd6cd03e2bd6be665848a202"
metafile = true
