hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "17df3203c357ae2bbbeeb2eee65cf23311c4ec7a035055ec2ae988db51243a62"

[[files]]
file = "config/puzzle.json"
hash = "21829a5d69be72b4202c975210a69c9331d75cd0cb7a9cddde56dac1131774ac"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "d16ef4b4dd9d1cfee220332e0246840ca3893a7c0cde99a299f717b63bd8dc2a"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "62b04eea085d727936f22e03d11ebadfae7490fd58da9048409b94c6ac21af9e"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "56e38e1d6039cbcf32c68416b60be42a4f5f3006c3caf50eb1eae1fc03580e86"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "c7983abfbff136519ffeca3ac75f4db10c81d7ad3adae6f4e1f9ad509a04c817"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "e0175393f767dc9d1c61ee6b69db461ea1d6d26b76c6f07503d6724edd009c89"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "51336712e25933a4b3ef553958ead09ccf02a7502b02b4240ae60c381b1858f0"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "03446bd8438e32366f310541f383bce5cdb2154fb5fb51973a7f3cf14f3ef173"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "d8eec905de29447db4b7a8c82c317033104f812190e59a6df1bc80b1bbac94cb"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "51737ea18619d5d6f55a8c7aff5ac0375ab8387a68698baa650d4732c8e38df6"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "2fee62477522b340fb814284e126749bd7858d2f7c17a2400d09644e5c4d725d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "909e2467c0c277d63fe881ac80e44ea69ed85fe70c09665f2350cf92494294cf"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "39e289b38f9dab390f1103490002374eaf98c688de33cf6abf1e72dc9a5b9c92"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "0d539bf48acbab4079d41894b35a8eca1c68368738fd713de08acecae1dd8509"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/yosbr/config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7fa2fdbeb82f6838cdfd4e3c686f31aafba333e505509d75b98883fe8a17f450"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "c602ad2f5d370579a6f530355b2c60852fbbbfa6c230ebb568cbf79ec290e76b"

[[files]]
file = "config/yosbr/options.txt"
hash = "4c4b9d86961d5fc9213f1781d51ad6f671ee70bffa1df30345356b30c02e7c3c"

[[files]]
file = "mods/animatica.pw.toml"
hash = "471190b2467d200f034d7f8b38ac932cb76082724439fa500dce4041a431b1f2"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "61e83f271c7e16618b26ee427e87d9ced073c2e8edcc94dbdff76aed3f5a8069"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "eca4f4b015ce8aa02c9fd68959e067894967744f3602f44ca24e93c21a0cb39f"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "727c319290b015a46f54f379fdb32b1a8eeb649c85bb7409fe3b9ffd3ebe5d22"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "3f2fabb5b9e0534db50a787a001261462354c0b5c4a19a2a35f8b271118e2909"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f90a836fdbf3d3d66f5a670213022711aa4d1762edc8265a8e97b9606cd9b49e"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "e1ae0274ae51f9ac63e47a7009ba183fa395e01a2b45be12cc9d53803bc20858"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d807461a67a231feb0e1a23929aeec7117f6260a565a6010e6cb45b386debdb3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ffc1f6d147394bfeb65b2fb9a78ca7d3365cbf5192c31af1312bc899190e4e34"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "2440a3dbb326c4993cb00d5619581017cc783981f8cbaf8ab53bd400d1e5bbf5"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b668875d7f22033e43efeef4c1772f8567d6b33b06f7b16e17ccb3bbcb23dc47"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e4368d03d9745fa609d706cac8f595f061af10fdd0833c17e4e027c2d607e1fa"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "807fe13ed38451a7872e5ea0643eead9f6cbd02c957249eecc9be237e833f5e4"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "6f95b9e670d557f852a798489d7b5ec48ed8ddc7e8e1809ff06d4b187d17aac9"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "b5ab49d85a98416b5e930f0b674323a45d562822cf05b23065af57f109891f48"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "f2591d950351aedab7ee4d59d492f5e5570dafd071dba3b390d5a7cafa89ab85"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "112b6225f1559851e105b5b9b407d2a626579f443419b26386f26d0d06cc7267"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "38a2c415fc59ca97c5297542b67daf477ecce294b3cbe2fe530193c879a252a6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4e5b3f0f1f62498a4dfdc4524b8c72ae4e91576ded5f2510cc676532b5876c95"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "fdebc54ee80be90757fae74011431710cf07d1df5ffaf81678a5c2c8f2d32a2b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "369cfc369e41a6e9f23343a5f7d0547acf76aaf88ce0a221ba7f67d081b054fc"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "333b0a827bc10800ebfb5a83f6f540f92553d3d57bf47e3f183e0b6d935597c0"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "3c3f1788a62da45c975e150cc851ca6639c7d0dec10c43c9500f933ad15b1768"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9480f9e11e91eb82ba616c5c622c218d7b7ceff6599a3348d557eb1a1ddd41f9"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "82d8ed6cc769257376217023070f00052b4197abc723c736f12ddadefe00591e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "ec64297b6b7f82ede5ecc46a82e8a0e8dc8b730ee2ad763427b7043389b7a072"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b99c1cae57386de36e5a6dc1d247057d0d5c0e9c5a5563b67d078ea7975919a9"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "3fa5439f34ada944b04d1abbe6e78e49ef5f561b336511a2c5cfd85c7ddd1e03"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "6b9a5755df72a262ba648f459c72d130211f859811b80b69aed1d47ea1a7aad6"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "54db897cb696867285ee42422e4e57ee9e30382541c5e7c85bdaa3324aae63fe"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "4ef251bf925c957e46fa3b223933425df85611d4ddf0e7a04949b38783800a65"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "340753cc88ec9db69e6f17a0ccd0eee24caaef85ad81e074bf44fb6cec7c787e"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "98bed93269e490532d84cf27cff645a531d0d27a1088816298517e5f1afcd621"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "57a8156ca507aef595456aede3dc9f8ad5b9e9e835900c22f9817b79be1202e8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "99f9628800ccabd189b9bb28859f01caaf9ad672f247ae875e3eaa5f965f9406"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "375c30762ed56d05a81beb277afee7fca7e1cb68fff1828c7e9d66a85ccdd3c6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
