hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "77adc932c3e336b4f81c985a4a2b68a127fff12f3cfa601da6539683995ba777"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "a737dd82279403a1a22b4dcd1fa3f99915f4feac38879042a8b1da6a4ccac199"

[[files]]
file = "mods/animatica.pw.toml"
hash = "58134b8f4cca95555746efad25cc8a56c39ed57ba05f78d3aa61b603d378180c"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "fe5f1014f6711013213e118c9defb3c41357d0ebdaa658f15d35c76839e419a0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "677469580950a9ccb8b14cda84f187d19cca5a8062cb0f0421816a4bb3af9808"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "04caaca613928c8d4e1d3015332a74a43be6ee0fd7693011d2aa91f56d13f768"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "f85c908d960ca1baf260bbcfa672b1bf46b633c9d71870c43a14be5b4187904a"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "7986f751d84536043edd1e67178554f6d4c3f01409feae6c151afa7854db5fa2"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "f32c30de1ae7dbeeae00b654eb15ea358c6d26f631dc292bdb88dba9c30a8cc8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ef5594aca1039c06c502f9d3f4a709195b727abb3b2893652dfe38d983ff87c2"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "a6ffb726bb2c918b172b8c2e1d524fa3e621431242de84b07c5ed0d238332947"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "20bd4cbff43edcff50312e24802538df9c264507fa35c8c8713f35401c03bbf8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "bfa17fc53b5b8d7cfb09ed49661e038864e9f89d79c7378377ecd3aea471d7b5"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4ba3ed5a7d60f618df89d9cd776a6ca79f8867090bd47c24ae3e6de6eafe594d"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "03ff6ba60d550b285dadec9bf0344e81d5c188648d383e00f869abdd01a19ab8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3039ab6ea60a5424d3b7d31f8fbfe16d3988b9a0bb7c670ba949743f63695ebd"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "bb9a29a48b27e7abc0799d4393240ae2cdcf7d64341c9a63347769173f8bda2e"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "2b2a86c2dd5a5d781065964c53434bc6c73b6b6006bc1e08ea0b815985b25ddb"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "9baaaf98f919bf3258f50ae0b8552a53c16d298650cb90d48cbec6f96d1ef556"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1f6c74d7140e368e85df87d1bdbb4b533052488dcee7e23ecc1f699dfd2efe82"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "08114da8c86093301d6b6e07349709395599c4731626058a27a5395dd6369ff4"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1ef554f7a8d5f7ed4bc21316e034eeef3430dc306012c0a706bd4c3e4ac253aa"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c7acf68591c9e2e380d2fa7f01bd3b8f37a9e91ee53c59e043c4189a86c162a9"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "82e7a1244febc6b4699e17bcee523567efc9c8c005d67057f9c4c40e7fba2a5a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9752dfb3a2284f00d64d338df2d740e5c55bfcd4eb1aa7819fd9915a007468ef"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "81ea6ca456261caaf5df55f5e5ba0dfbf04e9daf23cd93e00c35cec4d3fb27b3"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f4070441d1f1bdeb3e6a594b5ba1c3f314b8f13815a67619cb38621c0f6a1fec"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "3ba523b0e2a61388644998f4ce0e34bffe2b4bbe59d5b4bd8e467e52fc4fc21a"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "78946e7851174a7462125185cb6306f5bac4fe5b90a3f4396cd8a79d56084661"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a874985359eaa4317b3242136fe65b86207a6d5ab55e0b4aa8f37b90727f0487"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5ca4c5d71d0e9fbcc9a8561fe3e05fbdad8150d98e5976e9fec8f62c103ebeea"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "4044051a3cb2ae86edab32775bbe99f2c379afde47d7fe0b1f8ff2897447a59e"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8dbde9d801d11cc513e827122090ce34b01ac9fc0514be34758ddab2adff97f5"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f59ab3633f781c5b5af3234f694da4c4d5195c9211b1ece7e410b54ec1a183eb"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "0350ebc0042d86eb03d1ef9c3615ded0a45e0e75a641fd6077b8d5e2fc3f6164"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "bedeab81b949543d6e5ba34a496f63543cdcbc33982a44794fc14de48eec5b8b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/resolution-control-plus-plus.pw.toml"
hash = "6189a3ed8000d767e717392521a8fd1efdf4ce01ad82407990c29c7f919df980"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "585e3b8144192b82e4fcbc36c4b1d8355789feb034acf8dd0d7f6c46692dd39c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "56a0e243140dc1dbdb89c5a7a1cbcbe6e8d6da5499242bd1eabf548bbb8e3481"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "bccd06a5e9fee3d41ceb1c3746619be49182cc5be4fa9ea271158245e91f5061"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "1c137d989a144a658c564d77658919ed50c6a09ea8624037976425f0b4c7128e"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "03ca0fd071811d0bad860d35c7ef789867d71d94a33b8be70fd43fa43edb505c"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "191bc56c6e1f4125bc47670320daaf51d10f18cc1c7011e2beb44fe56f4e582e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "30803367ec9fd1961894d04bb97e3ed278fdd6b5eca1a268acea681f1f0b4db6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "597855edd33ebccfdf3aea7b3f68092d4c09182a2478807d573dc60ed5ff3109"
metafile = true
