hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "6342cac5becd8ed93662e5eca79ab6d00a7c6f7f1cab7f94d6929ddea6f72aff"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "f0dfe4d7e5f928318f910ed4f2f0d1dd619d9acb80bbad15cb4850c1a73d0b01"

[[files]]
file = "config/yosbr/config/cape-provider.json5"
hash = "81d978242279e9ab88842153065513852ff26735fed3318460030dad36c0904d"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "bc7cfadfe7121fdbd356c7992705ea6f484de518d3fd473eb8c59ea93e79a04d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "aa798e887fb1fe69563a06e259dc2be59bcb3baf45ec05c1ded759ac6c1ff3ef"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "ef55a85f0905e41d93de2b7e53266d393bf58f43917d9b15ea8f66b757a5996d"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "c951505f545e9d7f57ba66201609eac1792469e22fa13efcade818fc8b61cbe2"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "c668b4ad565c58243a1e0eb71884b17c77ab2242d983075f12dc2666060709ba"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/ok_zoomer/config.toml"
hash = "a7c05cd6ad8a8fcd1399b40aefe221c9cbaa67e58fac4b477bda534ec92d9ded"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "481193336b67c5a9a82beec77880556f3b92fd792cd8ea4414a904dd66acd733"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "5b24c9a57bb6092df95d9e8ec3c79574103967cef4db94508b9b172df1e447e5"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "564937e9bb15ddeb6741ce741a35486bc71b2a9a178d176b6107cfcb30747540"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "c602ad2f5d370579a6f530355b2c60852fbbbfa6c230ebb568cbf79ec290e76b"

[[files]]
file = "config/yosbr/options.txt"
hash = "a737dd82279403a1a22b4dcd1fa3f99915f4feac38879042a8b1da6a4ccac199"

[[files]]
file = "mods/animatica.pw.toml"
hash = "c5048fc150b79625fe3304de6b57643436f6e232f4f5493cbe0476494e54120e"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "284a7ccf2dc6ff43378230c252323359634f2b566212924ad0f138f4203079c6"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "321066a558542e9b7caeb2e3a93eb4bddd4d3fc2e3d39afbd02e902b17c8f897"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "04caaca613928c8d4e1d3015332a74a43be6ee0fd7693011d2aa91f56d13f768"
metafile = true

[[files]]
file = "mods/cape-provider.pw.toml"
hash = "c5c6fa0deffa311658ca3225c54f94a71686b66134bfad1e3bf819e2ba977c2c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "7986f751d84536043edd1e67178554f6d4c3f01409feae6c151afa7854db5fa2"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "ed36bc2969810d3a4d9575e72ff0c7b3513b51cdc2aa00b8edff04c29efb239f"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "f32c30de1ae7dbeeae00b654eb15ea358c6d26f631dc292bdb88dba9c30a8cc8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "04851cf23a0fef9e213180bf5926b705c5ad2d0b04d41934b915cc1ccfabd841"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "883f5688d32b11100214279e4a04e2a9ba788dc1d99db611a9f1aca946c07c9c"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "02551a8ead8bb69124fc6c20e0c557b07d6e50f8aaa0b7f586d8300e6f535e98"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "56f606d60928596e8fc3aedb55f73704738ac4f67c881d8bf6016b4991984d11"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "2f9f9ae2453a22b27d8a7eef2de12a1c0c17c6783c77a52bf76aeb6b75c96ab5"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "f3f7435f6bac0e704df49ddbfcd28db568631d42a1f6be79cb95d743e71233d8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b2f2ef63febe17f277635827ca474e1aeae321e8a82bef78942116f95d00250a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "098d6976a738658ca490cc58e9fab19f06cd1a7b23199b6f1ee108d866333e22"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "072c34f2d98bfb4a06fe70804d5d5eae140c597522b2e1eec4d7f71c0652b551"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "08114da8c86093301d6b6e07349709395599c4731626058a27a5395dd6369ff4"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1ef554f7a8d5f7ed4bc21316e034eeef3430dc306012c0a706bd4c3e4ac253aa"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "9c58c6f6299c9ab982847248be076b6840df69ce6b647a2a18e81d9a1cbeaf19"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c77d1172ce556528082c3dc4b6abe0d5d6b602d8a58fe3118cc7178610210149"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e03fc0b0c151c5c072ac399d27b5c4268a093c41be73f3b1578d050bb49211f3"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "06d953295265b2f415532373736703632cbddcfe916a8f6534ab3006f57a6c4f"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "aeee628da27bde07e28866859d52ce5f45e45fb39fcc4e5cb48cfb9174b3cc69"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "df9d69dc784ef61e99064407952d34c294f62fe1155b5260f825bd9a82e2f3a2"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "95de24f2f2d9c9fa4dcb33660bd6fafb2101a5514f718d00b207f48da26b64cf"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "732e3a5fb7d7c41c380d1ba92118293db75d5a7f2c05a6df6ac04c54c4bd1a22"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "78946e7851174a7462125185cb6306f5bac4fe5b90a3f4396cd8a79d56084661"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a874985359eaa4317b3242136fe65b86207a6d5ab55e0b4aa8f37b90727f0487"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "88c6edc1712f4f0cd915cd723b9e0296924d454b3855a719d2962103b2b92bea"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "4044051a3cb2ae86edab32775bbe99f2c379afde47d7fe0b1f8ff2897447a59e"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "00942cd2fd2775f47e1451a1705fcc0bc282bc0e7f19eafbaea70866478244b4"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "8c3777fcf9615b961fa6c1f44ae002cba0d0d16cf62041ef2fa23e4e481bc56e"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "a3b6cfe494d8ca3b080ce18d94d3218d7a76545d8b05e3f0b92a2b15c45c97dd"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "3033ea653f49eef17c526fbc6475cdc32ebfc3b3d984f4205b3ed1cd4a08dc0c"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "854fee52182885afc5ac536cfa24baff9d1768ada6c9164aebd44112c7404cbb"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "af416ddf58beeb89452503266f7aedf39d4a1c20ccc36c9b40632c22a6b91b7b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/renderscale.pw.toml"
hash = "f556b79b6dab86608cefbf643663298256c212eee9ec46e02000de674ade6fee"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "56a0e243140dc1dbdb89c5a7a1cbcbe6e8d6da5499242bd1eabf548bbb8e3481"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "09d2dbee70e91e8859e6f62e4181a80264d6dd24cc686fbedb93dda9f69fdfe6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "4b34d0b0a337960b15a16b5cb57081f0eb76bf408c0670b8238d0bf713226dbe"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c1db2ff822b1aa96dbf8642d73c5811d06669855a9de0fef60828c189fb7c4a6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "b33036850e44c6a79c3995027144a1758ca16e0f46c36bc068870575e2f4fe26"
metafile = true
