name = "Additive"
author = "SkywardMC"
version = "1.37.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1028c362e209f1062ca9834c8b8c86bb34bcc3958b1db698be7a8cb9796b0bfe"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
