name = "Additive"
author = "SkywardMC"
version = "1.34.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6daa98729b0fb4f347935e66ba80cd328300e10dcfb0e12fbffead76165853ee"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
