hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "4b0fa9e03aafc5d8dfd10d907d7e58df5c8d0800954c1136f98641e3fd485e0e"

[[files]]
file = "config/puzzle.json"
hash = "21829a5d69be72b4202c975210a69c9331d75cd0cb7a9cddde56dac1131774ac"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "d16ef4b4dd9d1cfee220332e0246840ca3893a7c0cde99a299f717b63bd8dc2a"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "62b04eea085d727936f22e03d11ebadfae7490fd58da9048409b94c6ac21af9e"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "56e38e1d6039cbcf32c68416b60be42a4f5f3006c3caf50eb1eae1fc03580e86"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "cdf61af100d8a29e9bbf26cc1b7ad8ae29c82357831705a97bb1dffa8ab386fa"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "51336712e25933a4b3ef553958ead09ccf02a7502b02b4240ae60c381b1858f0"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "84825744a3386b5194422e99eba7a3f49f0b29d4a9eb74a11921fd558d4571e8"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "bd5d8eaf56e9ddb5196a85a5713db7e213ed88c8895958f33c01464a1cb0a1d3"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "1dc6a3aef057f6d08a802abba3c64af5d604078059787da31d253544c67e8904"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "08c78ab862dbb711eaa56f41bbf4696e3fe7d7c5882e864bdf6586a0e67234a9"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "51737ea18619d5d6f55a8c7aff5ac0375ab8387a68698baa650d4732c8e38df6"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "0d539bf48acbab4079d41894b35a8eca1c68368738fd713de08acecae1dd8509"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/yosbr/config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "6ccf73c631ecef6b9a5b6a9cb67b4ac117a3b131ce0b4a884a3b4ec1b537aa0f"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "c602ad2f5d370579a6f530355b2c60852fbbbfa6c230ebb568cbf79ec290e76b"

[[files]]
file = "config/yosbr/options.txt"
hash = "96c989dd0d3e12f5d042f0964452365a9add38effcd6fa3d079474d25420d524"

[[files]]
file = "mods/animatica.pw.toml"
hash = "b494eb2872c5eb3c498e147be24a62e2c62485e375b9b99c15ae0faf8f9dd2ca"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b1ff809ec34348860c3a403f3d5210f7386ddcda8f0d19c5ff4533fd22abeb08"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "83d8a8865dfe81276fabc0c7085106a760608c0a3d569716fc77b3d0cb4d4c0d"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "fd235eacb6d28aae0ebdfa0de95ac33e4f1a6ec67e16fe8074153665b3b0f55a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "86498eb7f9326155844799dc57c1372fc5000b86f046994162cccd2e480a96ed"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4cb02206331c9a6d207681b2e40b4b8648a462b0c31e6e634200a01b592b1d3d"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "1a40260b79727502120cbf6a83efc62df915671677bb7e910aa8c65d575d0a80"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "78b4265cb588c34e3f144857d011413dd54953d8301bf911fe31dc0a37e5024a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "beaf8fcc2dbc9098a414bedd5a8ca156084b39f20517fac2ff60ad57f5767202"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "3ddb12a19403eb453fda1c23fd5124b0451db66eb6bf56a6b8b396b6f5fe17a4"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "4e2a60e26cb6760c58dd2ed193f071c430b76cb542ebda0394cfacd220c12362"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7be1e122e9ef8f1b7f2df9ffccf02cf83a52d0a53ae5ba7d07ea7bd3cc149101"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "f33a392dbbc1e518ebca8929707b5f6c38d59c67fb0b30a30a3ebae5e3d59c73"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "6ecd2a8ab1d0583d10fc4df74e9a0282055b497d61467a75bec3adaf88abb143"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "0e72ac12907f4fb5a499a459cc2c64f9225a0c77ee59e76c9360ff0d3479aea2"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "5907619c0a26d32e4b7b2f6de98eddeb192b523adfb6765dd73c3224e7be175b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4c1b893d87c51588985c483fe33193ca03cf3673de998eef6eeb850d8928e7ab"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "93255e83ba1978a3e41222593a935413bbbffd4a3014fa74739446ed66ce7f89"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "064fafff245baf812342dc9af4acf661dec663bab2a4067c65a27fa00860efb1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "09d31307f81a06df5ab65ff57c2c830180bbc1138bb8326557172b0a883d6b8b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "83a212a71370bd6cc3133a44aed97da0d03492b525f4f0aff5e5a76922608b0b"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "3bca5a31f4a469ca2c833cab5b87093ce809c2b599d6f93c19f78b69b78828a5"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "3ffe2388740cc111a332082f56e37bb4b95764035dfe5d6dff81db8a35d4cc4d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2dcac529633f402a5a325b8031bf15a06db668b912e6be1596836bde3afb17f1"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4ce761e594c255a802bd4b0b4b6312e740130b17d77764c389cef4c8417ae8af"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c6932018158da544553f88b977bed1946f59d9c86685f2023b0a9ee196fc3087"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0ac90dcc33473b316b975601f5c69f172e9babae174e7c85ec24281e31903934"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "1afe5d10e148d3d727f70bfc065e0e65b9992bcd1904dcdc3f29c201a6d4dd15"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "9f099a192392ee51ed679dad76f74806cf1c2fa8c8a37ae015f22c208cfa8236"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "e4c981864080221395f462c5a2ef1ccfd38aa6b16ca10879a4b5ef4f60828a7d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4b3e56fec52c8a95bb59e11f745be3a5ed8a527714cb4b5fb8ac5b7bf3cc662f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1ab96020d0954a72b5cc150b375f57cf8968ac2c1809a000472076f8675eb9ea"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dbc278de3d507cad99715d17c2f4858e58cf7ce5e76c9c59525d5fae7c05172f"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c66028d555a347562589645179fe8834bd04d48b78c9a667f20b4178211dfbb3"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "64cc3a69ccf183d56da3c42383918b90da3825877cbb13f712bc671487903120"
metafile = true
