hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "aac3264b90df2d5233cf095b3280f9f458ac47e087ef7fe64facef1c4180032c"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "bc7cfadfe7121fdbd356c7992705ea6f484de518d3fd473eb8c59ea93e79a04d"

[[files]]
file = "config/yosbr/config/cull-less-leaves.json"
hash = "e94813034405ef213afd650f1c7e9ff454a04435a8b72a74a73d470db41f5abc"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "a737dd82279403a1a22b4dcd1fa3f99915f4feac38879042a8b1da6a4ccac199"

[[files]]
file = "mods/animatica.pw.toml"
hash = "c0fb764563c122328f9ba69e7d27c2b3b2e21fc607782affd6710b943f03fe75"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "adf5896d6329adf0234a6ff63e6b7244c9fb3b304c1f6f4f7bdb44b72d38bb36"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "62c99a9cf83e5f6ae2c701bafe09b12b31c59d215194d56c7bb9e7ef6f291928"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "635275e7ff042568ac2279602371e0da61eae9b07d7486b5b357f5f43d83caa9"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "4c712d7ad6d2ddb130b845c3b2c660be7cb7795db21be00b130443730719305e"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2e1ad62031e3700de73a87957a4acca747436a4135da695705cb5d293aa0890"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "1b45a03526e1da2588157a25168938d240e89e9dd64c3295d142ce9e9314c145"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "e4a437ed5c3f631fd4787e6ad4d61295654aba9d07528a5b692b8e917221ea0d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "8697b0c71170d6e9bc4c30726581a63ad0ff9b15dbc810e295169234a6a0849e"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "71644e8041262193332f28d24b649c06c81074a983c6e3acd18b62a117b68b60"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b8270928d44781b9e59982d376bb3cc0d24089ceebef3c79d3e1e881ba7ece60"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0fb4ddac158d652d5c8774b7d58ae7c211d527cf4e58b83280c03637d15d72d0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ae20b3e48ff5681959c7f881877d410193140c6d07e035dbdf2eec3ce04dc96a"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "359dbf210e6657849bb7496155766cf1ae3030c83547744f136209a8c1594a80"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "d68580d9f12188c65baa7b33451a83ba336df142ecf38397b3ea8523f4db78fb"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2d44be0de504bd05e2f6f2e4644f5d7afd2401adcdff92c19871db204e121988"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "967a780be97bec40b8bca4945a053ee4fbd05d58e218c4fb803959ac0d0c7f08"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
hash = "9f4b3ab255d63cd35fd021a474113d121cf87f1e888ce648e9f66c8450aa9c5e"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "ed4487cc1613cc53daa5188730653a4720728971553315dcea7205b28f914f1c"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "ae83dfcccd580352eee3cf509ace37f67f1bf0d2862d2d9c9d64d8909892d2d4"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "26b473edf76a38c7f6f883381b6a42a33eea992501f26c46bae8b6149c86e234"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "68985a3f3d2a6f829783c1bdbd27f195556992fc2c0a9738656acccf38d8c97a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c56ddfdfccf143c8c6b5b93e9555d1c2d80ff7c1bdacd91dfede65785fa686b0"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d7cf7b5f76fdd8f9c63a95c9d82bce7162321232675b53d7b54aebaf537d70e0"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "e2e40b63c7c0aff577b89078a3205cb3ddc773b5c648e2beefe0883efa18e40d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "3ba523b0e2a61388644998f4ce0e34bffe2b4bbe59d5b4bd8e467e52fc4fc21a"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "2a79f7fb98b7073c926c6f87a93473f5714cf82a2ace7f344e4e2de4a33e0233"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "e78faacb02c5ad86a31ff1178d48c5b231433bb1128584c987ef60224057fb75"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "c1687f3c586612a2a5ddd5670ecc469cecaf87b7f62e0bfd4727e087d46ca4d8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "f4b9d7acc345b8df6dd13e19b36658cbca476abdee703ee6f38c66d33e8fa763"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "6c61882bbd734f1260d930c860ecd183e089e3d878c4faccee0f73acf65c18b1"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "19ffee4641700ca73e541a59638b0798a2d8fd66b5541d3fbc24a32ca7b62be1"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "a6e087aa1beacb72cbfd77e442c78329b8a3c8af71cd3833078ff4cc7186d64f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "0f9916dcded3aac68d56113e9617bbe3db5ec9036bd9bba784bc40a961b0c9f0"
metafile = true

[[files]]
file = "mods/resolution-control-plus.pw.toml"
hash = "f0dcbfc4f9cca6aa877c806b357f02e3be9fbf001c331b321f6855773129785a"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "058f62395b41a3b18121bcd961320cc8fd8460a34a5ccb4f07552e42ff19df4a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "dbbeb7a8f32fdbe0d5e44a8c7671ed2297ee8d12d4610500ac54742e70b4fb53"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "ff2f782be8090072041d0cd00abed11c1a22dfe2d397cd73e042f3b449954588"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "2f64975888aae7f9dccf2b5a7f0655148e93b44256d6b0649d9fd17eb97d8622"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3fdbd6ec9aaff3bc16c2206c64ec38e81b167e1736ab24840a2d0e9247263863"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "5df1b8ef822fe9987a65d412936909b4d700872db2ed107d0092e28452999101"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "f1f74f07924a5b0eb57e7c662c2e3f8c56d50eaee0dc2cb4cb40985af8eb9cf4"
metafile = true
