name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2760322cc2a480123440d120368f8d2b00824ebb5e6c159fadbae00073d4e43"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
