name = "Additive"
author = "SkywardMC"
version = "1.33.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5104f416bd11bc0ad6c1e442a5d178de8593d3ebe6d6b4f00ccfa658681d2d4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
