name = "Additive"
author = "SkywardMC"
version = "1.40.2+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cddefea31cb5cfb60b0e5ead354faba96cc8a95cabb62e08bd10322e502914b6"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
