name = "Additive"
author = "SkywardMC"
version = "1.38.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bbeacda6583a6e6dff8be48b8bc69f4e65e11b1a62b4c93d2a0674b4f3cc80f"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
