name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a368860124c1cb8e254b0c1489988fa283bd9f3abc519c3d52f254f244521ab"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
