hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "95d9933fb8d8d8d22dcc2eb4eafe3f1a91f02f1f2acc8208c464347b36cf91f7"

[[files]]
file = "config/puzzle.json"
hash = "017213d817c551c6bddb0cf3a1344ded1747abba66bb758c9c9effc39f0d46e0"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "1e673e5c776fc34a35e2df497d76d9081ad0f0b5c89ded17d2fd57fe1969272f"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "163f49d5c78bf76b1a112c792e936a5915994c472985585a9463134971abd607"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "54008cb6683821a7666db20867e55f71b7f90f101191cfe8fbaf1eb38f975e96"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "624ed4c30777968887c07194cc265fc66aea996a20f55c32f0df861bc8ccc5c5"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "a2470fbc25f1a7df9833c57ca6588a356da86d9ab46881e5ce0e505239943fed"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "6555c8c1fc4d773df097895dfb76fe004377347581d5731f5408fb9d138585a2"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "a8f46cff138e000d4ed4505cc2bfdc5cdc6e8b5588fd1b1e2d6222cd21e624e2"

[[files]]
file = "mods/animatica.pw.toml"
hash = "f0463f1b50e2c2ab3c726b14236b22e07ce9be4896528ede9d51486a212a5c07"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "31da0d40daba6f88d50d18ae5565aee6996657bcc34138f75622dd8f582385f6"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "617563db0d44229fb65eb660130d02d1a4d2f29233eda03b68d3273e700326f8"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "7a4414a95295f22f036699300878058ddf043659fc95ac1bf1d7f725acb0bc46"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f250d6778f5b8d03ca32913bea5ea677508e9bb6d8201cdebe005bbe9c3100ee"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ab1c014ce67654e89af779137bdfd1f6f22888af218f44cf5d83e943d0d5fbc4"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "1a65361cf2207ba6bad6eba3e66e407983452398c4ac5cbe5db0d8430b8a6496"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "b7a7971c44fd891674222a48df8999e379b8658d96ab9b3cf55c17c0b00bd1ce"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "78eae6c50ce595dc5e41b3be58f84218f614b8934e72d1f22348aa4bfa66f133"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "179d1b7ca85bd3202749e2cc95413daec331dd37dbcf66d07f12a2cd1c0ee397"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "8f0c18360533351fff9237b803b1a91fb86cc9b00d56e61f116076e654c9f8e8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "dd05166a94c4694bbc3a70acd7511b7642cfe2563d995e55d2850701980f87f0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "96478690ba4437d4f27af541c9365bd9dfd30674c3dc12fb3a1702e358a16a0c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "7f37944b56d4fcc531525e995ed9af77f28df47180372a6603ae7d3c3784fb9b"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "f80e4a46fab9a9c99ebf3193f2c73675f6f6659fcd740692e14501213f633c70"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "4d979c0f0902b82fc22fc60b741d3a9ce8331de9ffcc4f54658af92ff8ff8a81"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ff278c8a9a5e56d412fb2e7106790b0ac33b0a4a8699978f0ae4d5a2c70c63b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4146027b92b4885fddec00435233c61c3728b5e09265982ab187021519a4fa89"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d10d6632f398e4bc8f62555eab1d70a6624837741fc653f2e2a18188166c6477"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e416b18eebf514dea2014cf5c7fd3ee8493934a0b4e937509f15172ad271fde2"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "9e7bccd0c45b66352abd6fc0b1fa2745d564deb24f5c53dd20728847cf27dda0"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d398662ae6e9d87e89384ba50a9787dbeb9425902a18b0cd8239efd0b966b453"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3dedde5213176d72e1c353877fa44315945e8f3da2ba05f5679d81e9f558bb1d"
metafile = true

[[files]]
file = "mods/loqui.pw.toml"
hash = "8e273299702b68a6503a2d4bd42a05b629a207d84e7fcb6e7510276ac16e0c89"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "2a79f7fb98b7073c926c6f87a93473f5714cf82a2ace7f344e4e2de4a33e0233"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "c0daa1b0438a80083fed9145abe9760e6d4b0f5d3f091ea12e893c32072c8899"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f334786b4fa5a2cb0a6a952fa2a6ab74de3395c2be806045ea3a5905edd75363"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "979e6d73369f2e45666e49c387f7f4f9b266df1085d4a7a949039aac461b3c13"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "e5bde0bc121e4e034094552cda7d9cb4a1e23b6f8468fb0c701fa3f790a7dd89"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "b7feeb21fa9f9f4e7a9c417894c45f0f7a18a94acd17e9e860800c2950b53c98"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "b2db81b53e71fc73306a4a5bafb7a33662e2e3da6d77210db607466cd4c41d49"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "978fad60641210b2da438426ce9cb4f08b89ab677df05f1585848e3cc89730b5"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "0e59d00de821ce2095849c161e17e03d12a768d18859e813086adeaa71fd037b"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "50f413eb229b578c7dbb5d8665a8ad29e0221a4e16acbe62cb9f52e2bedaa732"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "f56b1d5d3619381aaf6f6db23baf8a37db263855d919742c92c419576a631651"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "975478c93b1218131fd48695cd7efb9bbe0d69125409940b015a7058e42fb6be"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f7c09e537f9db67804dd7df6b8ba3a0cfb63429ad992a99e8f8faba33187ded2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5e73967368d47038c38dc52fa298b45603fbe6baf2608f171638ff767178ad9a"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "44593cfab255a73ae00161802962950525bad36716eb00afda5f3e9bc6f4cba9"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "38c3d0b4d36bb16524ea3976cf1ac7fbe6c285529320bcaf5316888c18b3d01f"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "fc89119ebc9c811ef3cd852556b5caaa27c03eb8fb0014567dd83cc44024ba98"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "6ba173154c8fe78d78524902a420006e0f1af92533d990fc36d14e55f33327b4"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "2d9ab5d76c32219c684dbb599ef9ebc6d99148a084c38bc61c0cf1ea5f16a77c"
metafile = true
