name = "Additive"
author = "SkywardMC"
version = "1.25.1+1.20.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3098afc4221925455cbe6a1f5669f37cba9a5b27845fe6a8b707f759eabd9109"

[versions]
minecraft = "1.20.4"
quilt = "0.25.0"
